### ISSUE TITLE
Delete and re-index all if index already exists

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#10]
If the indexName already exists in MeiliSearch, delete the index and re-index all the documents (per batch)

**Comment by bidoubiwa** [comment]
Currently, when re-running the plugin, the documents fetched will be added to an existing MeiliSearch instance. 

https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/b47111ae46cfa2f1e06cf4910e9a72f45e5fc10d/gatsby-node.js#L35-L35

Meaning that if a previous document is not present after the new run of the script, it will still be present in your index. To avoid that, the best way is to delete the index completely and re-index the new documents.

pseudo code 
```
if index.getIndex() {
   await index.delete()
}

index = client.createIndex("newIndex")

index.addDocuments(transformedData)
```
