### ISSUE TITLE
Bug: Dependency on Meilisearch API Header : x-meili-api-key not found 

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/gatsby-plugin-meilisearch#111]
### Current behavious

![image](https://user-images.githubusercontent.com/19529592/151693968-5f93c420-f7d3-41c1-97a0-f4efa919d601.png)

When trying to build the playground project, we get the following error of The X-MEILI-API-KEY header is missing.

### Expected Behavior

Should be able to build the Gatsby project and index to Meilisearch

### Steps To Reproduce

In playground directory, 
Run : `npm install`
         `npm run build`

### Anything else?
I used a cloud.meilisearch.com instance with the version of Meilisearch as v0.24.0.

_No response_

**Comment by bidoubiwa** [comment]
Hey @shivaylamba 
The released version of the gatsby plugin only works with the latest release of Meilisearch: v0.25.0.
It is a bit hidden but you can find the information at the [bottom of the readme](https://github.com/meilisearch/gatsby-plugin-meilisearch#-compatibility-with-meilisearch-and-gatsby).

**Comment by bidoubiwa** [comment]
I think is solved. Tell me if it is not @shivaylamba :)
