### ISSUE TITLE
Add the `skipIndexing` option

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#12]
Retrieve the `skipIndexing` (true/false) from the options, and use it to determine if the indexation has to be done or not.
This can be usefull for example if a user is in development mode, and doesn't want to index the changes he just made.

**Comment by bidoubiwa** [comment]
When a user is developing his gatsby website they maybe do not want MeiliSearch plugin to re-index on every rebuild. We should add a `skipIndexing` option in the settings

```
    options: {
        host: 'http://localhost:7700',
        apiKey: 'masterKey',
        skipIndexing: true, // HERE
        queries: {
          ...
        },
      },
```
When this option is activated, the plugin should not fetch and index data.

```js
exports.onPostBuild = async function ({ graphql, reporter }, config) {
  const activity = reporter.activityTimer(PLUGIN_NAME)
  activity.start()
  try {
    const { queries, host, apiKey = '', skipIndexing } = config
    if (skipIndexing) {
      // quit
    }
....
```
