### ISSUE TITLE
Use MeiliSearch settings

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#14]

**Comment by Ln11211** [comment]
@mdubus, hello, what exactly should we be doing ?

**Comment by bidoubiwa** [comment]
Hey @Ln11211 i will be specifying more every pr on this repo but will do probably do it on Sunday! I will ping you here once it is done :)

**Comment by Ln11211** [comment]
@bidoubiwa ok ?

**Comment by abhilashkpy** [comment]
Kindly assign a good first issue.

**Comment by manavmodi22** [comment]
Commenting to keep myself updated on the issue.

**Comment by bidoubiwa** [comment]
Hey! For the explaination here we go :)

To configurate the plugin you provide config in gatsby-config.js

Example: 
https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/b47111ae46cfa2f1e06cf4910e9a72f45e5fc10d/playground/gatsby-config.js#L42-L67

In these options we do not provide the possibility to pass `settings`. 

By providing the `settings` option to a query object it gives the possibility to the user to add [MeiliSearch Settings](https://docs.meilisearch.com/reference/features/settings.html#settings) to the index. 

Example: 

```js
      options: {
        host: 'http://localhost:7700',
        apiKey: 'masterKey',
        queries: {
          indexUid: 'my_blog',
          settings: { // here
            filterableAttributes: ["tags"],
            searchableAttributes: ["title", "body"]
          },
          transformer: data => data.allMdx.edges.map(({ node }) => node),
          query: `
            ...
          `,
        },
      },
```

Adding settings should be done before adding documents [as best practice](https://github.com/meilisearch/documentation/issues/824).

Thus in the code it would add an additional step before adding documents: 

```
const index = client.index(queries.indexUid)

// Add settings to Index
const { updateId } = await index.addSettings(queries.settings)

// wait for settings to be processed

// Index data to Index
const { updateId } = await index.addDocuments(transformedData)

````

**Comment by Ln11211** [comment]
@bidoubiwa , I am unable to understand the assignment and I apologize for wasting your time.
