### ISSUE TITLE
Allow multi-indexing

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#15]
Transform the `indexes` option into an array, and allow multi-indexing to be done. 
Make tests to make sure multi-indexing is correctly done

**Comment by bidoubiwa** [comment]
Currently `Indexes` only accepts one object:

https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/b47111ae46cfa2f1e06cf4910e9a72f45e5fc10d/playground/gatsby-config.js#L46-L66

This was done for MVP purposes but should be updated to an array of objects.

```js
{
indexes: [ { indexUid: ...}]
}
```

Thus, the plugin should iterate on every query and apply the required changes. 

```js
for query in queries {

// plugin code 

}
```

`validatePluginOptions(queries, host)`  Should also be updated to only accept arrays for `indexes` option.
