### ISSUE TITLE
error timeout of 5000ms has exceeded on process 3 when waiting a task to be resolved.

### ISSUE THREAD

**Issue by TristanPeers** [meilisearch/gatsby-plugin-meilisearch#194]
Hi - we are using this plugin (which is fantastic) with Gatsby however we've started getting this issue `only` in CI (Gitlab). If I run the build locally on my Mac it is fine which would suggest some kind of resourcing issue?

```
success Building static HTML for pages - 39.268s - 2714/2714 69.12/s
error timeout of 5000ms has exceeded on process 3 when waiting a task to be resolved.
success gatsby-plugin-meilisearch - 9.715s - Failed to index to Meilisearch
success onPostBuild - 10.556s
```

A similar issue (https://github.com/meilisearch/strapi-plugin-meilisearch/issues/337) talks about auto-batching and changing the timeout. Auto-batching is apparently enabled now and there doesn't seem to be any option for changing the timeout with the plugin. I've tried different `batchSize` settings to no avail. We have approx 2,700 documents to index so not a massive amount.

We run the docker version of Meilisearch (v029.2) in ECS Fargate.

```
"gatsby": "4.14.1",
"gatsby-plugin-meilisearch": "^0.2.1",
```

Is there a way to change the timeout or can you advise how I can troubleshoot? 

Many thanks.

**Comment by bidoubiwa** [comment]
Hey @TristanPeers 
Thanks a lot for this information. I'll investigate to see if we cannot find a quick fix to this. Can you confirm that your documents are not indexed even if the error occurs?

**Comment by TristanPeers** [comment]
Hi @bidoubiwa - many thanks for looking at this. 

I added a brand new test page to the site to check if it would be indexed as per your question.

Unfortunately/fortunately our CI pipeline has started worked again (no changes to anything at all except markdown this week):

```
success Building static HTML for pages - 44.195s - 2716/2716 61.45/s
success gatsby-plugin-meilisearch - 9.816s - Documents added to Meilisearch
success onPostBuild - 10.677s
```

As you can see the numbers/stats are very similar to the ones in the initial post which is quite bizarre.

I will continue to monitor and if it breaks again, I will add another new test page to get you that verification. 

If there's any kind of extra logging/verbosity setting which could be added to the Gatsby build process that would be really useful?

**Comment by bidoubiwa** [comment]
Having more logging/verbosity is a good suggestion. We just need to define what we can log that is relevant.

In the plugin, we are waiting on tasks to be processed by Meilisearch, meaning that your build will take as long as the time it takes to index all the documents into Meilisearch. On a bigger dataset, this might be problematic, and this is what happened to you. 

https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/eedc486b765dc34bd9ec6fac81af8cea6f478218/gatsby-node.js#L93-L101

Possibly we can either: 
1. Make document indexation asynchronous. Logging only the tasks added in Meilisearch. Example: 
   ```   
    Additing 3600 documents to Meilisearch, track the process with its task id : `45`. (doc: 
    https://docs.meilisearch.com/reference/api/tasks.html#get-one-task)
   ```
2. Make `timeout` a setting that you can change. And still log the related task `id`
    ```
      Task `45`, indexing 3600 documents into Meilisearch, is being processed....
    ```

What do you think is best? I'll make an issue suggesting that change. I prefer option 1, this avoids failing your CI and/or make the build to long. It still provides enough information to track why your documents are not being indexed

**Comment by TristanPeers** [comment]
HI @bidoubiwa - many thanks for the updated info. I agree option 1 seems nicer to me.

Also - just to answer your earlier question, CI failed again with Meilisearch this morning so I added another brand new test page to the site. 

It then failed again when adding this new page:

```
success Building static HTML for pages - 48.206s - 2716/2716 56.34/s
error timeout of 5000ms has exceeded on process 73 when waiting a task to be resolved.
success gatsby-plugin-meilisearch - 9.794s - Failed to index to Meilisearch
success onPostBuild - 10.733s
```

...however this new page `DID` get added to the Meilisearch index!?!?!? Very strange...

**Comment by TristanPeers** [comment]
Many thanks for the explanation, that makes total sense.

**Comment by bidoubiwa** [comment]
What do you think of this output ? https://github.com/meilisearch/gatsby-plugin-meilisearch/pull/195

**Comment by TristanPeers** [comment]
Look amazing, many thanks!

**Comment by bidoubiwa** [comment]
It is released
 https://github.com/meilisearch/gatsby-plugin-meilisearch/releases/tag/v0.3.0

**Comment by TristanPeers** [comment]
Amazing - many thanks @bidoubiwa 👍 

Output looks great:

```
success Building static HTML for pages - 39.290s - 2716/2716 69.13/s
success Send documents to Meilisearch - 0.021s - Adding 500 document(s) to Meilisearch, task uid : "113".
success Send documents to Meilisearch - 0.128s - Adding 500 document(s) to Meilisearch, task uid : "114".
success Send documents to Meilisearch - 0.236s - Adding 500 document(s) to Meilisearch, task uid : "115".
success Send documents to Meilisearch - 0.024s - Adding 500 document(s) to Meilisearch, task uid : "116".
success Send documents to Meilisearch - 0.024s - Adding 500 document(s) to Meilisearch, task uid : "117".
success Send documents to Meilisearch - 0.046s - Adding 216 document(s) to Meilisearch, task uid : "118".
success gatsby-plugin-meilisearch - 0.582s - Documents are send to Meilisearch, track the indexing progress using the tasks uids.
doc: https://docs.meilisearch.com/reference/api/tasks.html#get-one-task
success onPostBuild - 1.416s
```
