### ISSUE TITLE
Create chore of project

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#2]
Initialize the project by adding the following: 

- [x] package.json
- [x] gitignore
- [x] .editorconfig
- [x] bors
- [x] dependabot
- [ ] release-drafter
- [x] eslint
- [x] prettier
- [x] licence file
- [x] readme
- [x] issue template
- [x] `test.yml` to test the linting

**Comment by bidoubiwa** [comment]
> npm ignore 
I think it is best to avoid using npm ignore, prefer using [`files`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) in package.json. That way you only explicitly say what you want to add in NPM and not having to remember add in the list everytime you create another file or directory.
