### ISSUE TITLE
Create Playground

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#3]
Create a playground inside the project, with the following: 

- gatsby project with blog articles
- Searchbar with [Instant MeiliSearch](https://github.com/meilisearch/meilisearch-react/) to test that the indexation was successful

Also make sure that eslint & prettier works well with the playground

**Comment by bidoubiwa** [comment]
See [example with gatsby here](https://github.com/bidoubiwa/gatsby-meilisearch-example)
