### ISSUE TITLE
Make batchs for the indexation

### ISSUE THREAD

**Issue by mdubus** [meilisearch/gatsby-plugin-meilisearch#9]
Split the indexation by making batches of 1000 (by default) documents

**Comment by bidoubiwa** [comment]
Currently the plugins fetch all data needed to be indexed and send it in one big batch to MeiliSearch 

https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/b47111ae46cfa2f1e06cf4910e9a72f45e5fc10d/gatsby-node.js#L37-L38

We want to avoid, in case the dataset is very large, a payload that is too big for the server hosting MeiliSearch. To do that, the best solution would be to batch the documents in smaller chunks before sending them. 

For example if your `transformedData` has 3500 documents, the plugin should send 3 times a chunk of 1000 documents and once a chunk of 500 documents.

**Comment by bidoubiwa** [comment]
Currently the plugins fetch all data needed to be indexed and send it in one big batch to MeiliSearch 

https://github.com/meilisearch/gatsby-plugin-meilisearch/blob/b47111ae46cfa2f1e06cf4910e9a72f45e5fc10d/gatsby-node.js#L37-L38

We want to avoid, in case the dataset is very large, a payload that is too big for the server hosting MeiliSearch. To do that, the best solution would be to batch the documents in smaller chunks before sending them. 

For example if your `transformedData` has 3500 documents, the plugin should send 3 times a chunk of 1000 documents and once a chunk of 500 documents.

**Comment by mdubus** [comment]
Closing as this was done with #54
